### Pre-hoc filters

In [1]:
source("./filter.R")
test<-read.csv("/data/sag_data.csv")
options( warn = -1 )
library("xtable")

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


Loading required package: spatstat.data

Loading required package: spatstat.geom

spatstat.geom 3.2-9

Loading required package: spatstat.random

spatstat.random 3.2-3

Loading required package: spatstat.explore

Loading required package: nlme


Attaching package: ‘nlme’


The following object is masked from ‘package:dplyr’:

    collapse


spatstat.explore 3.2-7

Loading required package: spatstat.model

Loading required package: rpart

spatstat.model 3.2-11

Loading required package: spatstat.linnet

spatstat.linnet 3.1-5


spatstat 3.0-8
For an introduction to spatstat, type ‘beginner’

### Cluster level intensity filter

In [2]:
section_filter <- function(data,sec,is_exc){
    li<- output_sample(test, sec)
    if (is_exc == TRUE){    
        type <- li$et
        data<-li$edata
    }
    else{
        type <- li$it
        data<-li$idata
    }
    pp<- create_pp(type,data)
    nn<-calc_R(pp, type, 0.2)
    conf<- calc_conf(pp, type, test, sec)
    res<-intense_qualify(pp,type, nn, conf)
    col.name<-paste('%',toString(sec), sep='')
    df<- data.frame(cluster = res$cluster, coln = round(res$conf,2))
    names(df)[names(df) == "coln"] <- col.name
    return(df)
}

### Excitatory clusters

In [3]:
for (n in 20:24){
    nam <- paste('df',toString(n), sep='')
    assign(nam, section_filter(test, n, TRUE))
}

[1]  159 5483   17
[1] 124 905  21
[1] "0109 L2/3 IT CTX Glut_2"
[1] 0.8
[1] "0079 L4/5 IT CTX Glut_2"
[1] 0.8
[1] "0004 CLA-EPd-CTX Car3 Glut_1"
[1] 0.8
[1] "0443 L6 CT CTX Glut_2"
[1] 0.8
[1] "0455 L6 CT CTX Glut_5"
[1] 0.7
[1] "0003 CLA-EPd-CTX Car3 Glut_1"
[1] 0.7
[1] "0439 L6 CT CTX Glut_1"
[1] 0.8
[1] "0007 IT EP-CLA Glut_1"
[1] 0.6
[1] "0061 L5 IT CTX Glut_3"
[1] 0.6
[1] "0096 L4/5 IT CTX Glut_5"
[1] 0.45
[1] "0074 L4/5 IT CTX Glut_1"
[1] 0.5
[1] "0100 L4/5 IT CTX Glut_6"
[1] 0.4
[1] "0037 L6 IT CTX Glut_1"
[1] 0.65
[1] "0436 L6 CT CTX Glut_1"
[1] 0.65
[1] "0041 L6 IT CTX Glut_2"
[1] 0.45
[1] "0116 L2/3 IT CTX Glut_3"
[1] 0.05
[1] "0453 L6 CT CTX Glut_5"
[1] 0.6
[1]  148 4983   14
[1] 112 813  19
[1] "0109 L2/3 IT CTX Glut_2"
[1] 0.8
[1] "0455 L6 CT CTX Glut_5"
[1] 0.8
[1] "0079 L4/5 IT CTX Glut_2"
[1] 0.6
[1] "0003 CLA-EPd-CTX Car3 Glut_1"
[1] 0.8
[1] "0004 CLA-EPd-CTX Car3 Glut_1"
[1] 0.65
[1] "0439 L6 CT CTX Glut_1"
[1] 0.7
[1] "0443 L6 CT CTX Glut_2"
[1] 0.75
[1] "0074 L4/5 IT CTX Glut_1"
[1] 0.55
[1] "0436 L6 CT CTX Glut_1"
[1] 0.45
[1] "0096 L4/5 IT CTX Glut_5"
[1] 0.6
[1] "0061 L5 IT CTX Glut_3"
[1] 0.45
[1] "0116 L2/3 IT CTX Glut_3"
[1] 0.4
[1] "0037 L6 IT CTX Glut_1"
[1] 0.55
[1] "0046 L6 IT CTX Glut_3"
[1] 0.8
[1]  150 2944   14
[1] 105 489  14
[1] "0109 L2/3 IT CTX Glut_2"
[1] 0.7
[1] "0079 L4/5 IT CTX Glut_2"
[1] 0.65
[1] "0455 L6 CT CTX Glut_5"
[1] 0.55
[1] "0003 CLA-EPd-CTX Car3 Glut_1"
[1] 0.8
[1] "0004 CLA-EPd-CTX Car3 Glut_1"
[1] 0.75
[1] "0116 L2/3 IT CTX Glut_3"
[1] 0.65
[1] "0074 L4/5 IT CTX Glut_1"
[1] 0.35
[1] "0439 L6 CT CTX Glut_1"
[1] 0.7
[1] "0100 L4/5 IT CTX Glut_6"
[1] 0.4
[1] "0464 L5 NP CTX Glut_2"
[1] 0.5
[1] "0026 L5/6 IT TPE-ENT Glut_2"
[1] 0.55
[1] "0436 L6 CT CTX Glut_1"
[1] 0.45
[1] "0110 L2/3 IT CTX Glut_2"
[1] 0.4
[1] "0067 L4/5 IT CTX Glut_1"
[1] 0.1
[1]  112 3334   18
[1] 103 661  12
[1] "0109 L2/3 IT CTX Glut_2"
[1] 0.8
[1] "0375 L5 ET CTX Glut_5"
[1] 0.7
[1] "0116 L2/3 IT CTX Glut_3"
[1] 0.7
[1] "0003 CLA-EPd-CTX Car3 Glut_1"
[1] 0.8
[1] "0074 L4/5 IT CTX Glut_1"
[1] 0.6
[1] "0079 L4/5 IT CTX Glut_2"
[1] 0.65
[1] "0464 L5 NP CTX Glut_2"
[1] 0.75
[1] "0026 L5/6 IT TPE-ENT Glut_2"
[1] 0.6
[1] "0114 L2/3 IT CTX Glut_3"
[1] 0.4
[1] "0004 CLA-EPd-CTX Car3 Glut_1"
[1] 0.75
[1] "0359 L5 ET CTX Glut_2"
[1] 0.65
[1] "0092 L4/5 IT CTX Glut_4"
[1] 0.55
[1] "0080 L4/5 IT CTX Glut_2"
[1] 0.6
[1] "0086 L4/5 IT CTX Glut_3"
[1] 0.55
[1] "0358 L5 ET CTX Glut_1"
[1] 0.65
[1] "0110 L2/3 IT CTX Glut_2"
[1] 0.45
[1] "0067 L4/5 IT CTX Glut_1"
[1] 0.3
[1] "0113 L2/3 IT CTX Glut_3"
[1] 0.3
[1]   79 2999   15
[1]  83 520  11
[1] "0109 L2/3 IT CTX Glut_2"
[1] 0.8
[1] "0074 L4/5 IT CTX Glut_1"
[1] 0.65
[1] "0116 L2/3 IT CTX Glut_3"
[1] 0.6
[1] "0079 L4/5 IT CTX Glut_2"
[1] 0.75
[1] "0375 L5 ET CTX Glut_5"
[1] 0.8
[1] "0114 L2/3 IT CTX Glut_3"
[1] 0.45
[1] "0092 L4/5 IT CTX Glut_4"
[1] 0.65
[1] "0003 CLA-EPd-CTX Car3 Glut_1"
[1] 0.7
[1] "0093 L4/5 IT CTX Glut_4"
[1] 0.5
[1] "0004 CLA-EPd-CTX Car3 Glut_1"
[1] 0.7
[1] "0080 L4/5 IT CTX Glut_2"
[1] 0.65
[1] "0113 L2/3 IT CTX Glut_3"
[1] 0.5
[1] "0086 L4/5 IT CTX Glut_3"
[1] 0.5
[1] "0110 L2/3 IT CTX Glut_2"
[1] 0.4
[1] "0370 L5 ET CTX Glut_4"
[1] 0.65

### Inhibitory clusters  
By relaxing on the area requirements, we hope to have more inhibitory cells passing through the filter.

In [4]:
for (n in 20:24){
    nam <- paste('dfi',toString(n), sep='')
    assign(nam, section_filter(test, n, FALSE))
}

[1]  159 5483   17
[1] 124 905  21
[1] "0740 Pvalb Gaba_3"
[1] 0.45
[1] "0742 Pvalb Gaba_3"
[1] 0.5
[1] "0709 Lamp5 Gaba_1"
[1] 0.6
[1] "0754 Pvalb Gaba_8"
[1] 0.4
[1] "0741 Pvalb Gaba_3"
[1] 0.35
[1] "0747 Pvalb Gaba_4"
[1] 0.25
[1] "0803 Sst Gaba_10"
[1] 0.55
[1] "0859 Sst Chodl Gaba_4"
[1] 0.5
[1] "0645 Vip Gaba_6"
[1] 0.25
[1] "0792 Sst Gaba_7"
[1] 0.25
[1] "0733 Pvalb chandelier Gaba_1"
[1] 0.8
[1] "0641 Vip Gaba_5"
[1] 0.6
[1] "0639 Vip Gaba_4"
[1] 0.55
[1] "0663 Vip Gaba_12"
[1] 0.4
[1] "0708 Lamp5 Gaba_1"
[1] 0.65
[1] "0811 Sst Gaba_13"
[1] 0.15
[1] "0624 Vip Gaba_1"
[1] 0.5
[1] "1003 STR-PAL Chst9 Gaba_1"
[1] 0.35
[1] "0682 Sncg Gaba_6"
[1] 0.65
[1] "0743 Pvalb Gaba_4"
[1] 0.05
[1] "0797 Sst Gaba_8"
[1] 0.5
[1]  148 4983   14
[1] 112 813  19
[1] "0709 Lamp5 Gaba_1"
[1] 0.7
[1] "0740 Pvalb Gaba_3"
[1] 0.6
[1] "0742 Pvalb Gaba_3"
[1] 0.5
[1] "0754 Pvalb Gaba_8"
[1] 0.45
[1] "0747 Pvalb Gaba_4"
[1] 0.6
[1] "0741 Pvalb Gaba_3"
[1] 0.6
[1] "0792 Sst Gaba_7"
[1] 0.2
[1] "0645 Vip Gaba_6"
[1] 0.45
[1] "0641 Vip Gaba_5"
[1] 0.15
[1] "0803 Sst Gaba_10"
[1] 0.3
[1] "0859 Sst Chodl Gaba_4"
[1] 0.65
[1] "0783 Sst Gaba_5"
[1] 0.75
[1] "0758 Sst Gaba_1"
[1] 0.6
[1] "0663 Vip Gaba_12"
[1] 0.4
[1] "0779 Sst Gaba_4"
[1] 0.05
[1] "0795 Sst Gaba_8"
[1] 0.5
[1] "0814 Sst Gaba_14"
[1] 0.05
[1] "0777 Sst Gaba_4"
[1] 0.4
[1] "0811 Sst Gaba_13"
[1] 0.05
[1]  150 2944   14
[1] 105 489  14
[1] "0709 Lamp5 Gaba_1"
[1] 0.6
[1] "0740 Pvalb Gaba_3"
[1] 0.3
[1] "0754 Pvalb Gaba_8"
[1] 0.45
[1] "0741 Pvalb Gaba_3"
[1] 0.55
[1] "0742 Pvalb Gaba_3"
[1] 0.3
[1] "0803 Sst Gaba_10"
[1] 0.45
[1] "0777 Sst Gaba_4"
[1] 0.7
[1] "0645 Vip Gaba_6"
[1] 0.45
[1] "0859 Sst Chodl Gaba_4"
[1] 0.55
[1] "0733 Pvalb chandelier Gaba_1"
[1] 0.65
[1] "0747 Pvalb Gaba_4"
[1] 0.7
[1] "0792 Sst Gaba_7"
[1] 0.2
[1] "0641 Vip Gaba_5"
[1] 0.05
[1] "0811 Sst Gaba_13"
[1] 0.5
[1]  112 3334   18
[1] 103 661  12
[1] "0754 Pvalb Gaba_8"
[1] 0.75
[1] "0741 Pvalb Gaba_3"
[1] 0.5
[1] "0740 Pvalb Gaba_3"
[1] 0.35
[1] "0742 Pvalb Gaba_3"
[1] 0.6
[1] "0709 Lamp5 Gaba_1"
[1] 0.7
[1] "0803 Sst Gaba_10"
[1] 0.8
[1] "0708 Lamp5 Gaba_1"
[1] 0.4
[1] "0641 Vip Gaba_5"
[1] 0.5
[1] "0645 Vip Gaba_6"
[1] 0.15
[1] "0792 Sst Gaba_7"
[1] 0.65
[1] "0780 Sst Gaba_4"
[1] 0.45
[1] "0797 Sst Gaba_8"
[1] 0.4
[1]   79 2999   15
[1]  83 520  11
[1] "0741 Pvalb Gaba_3"
[1] 0.8
[1] "0742 Pvalb Gaba_3"
[1] 0.6
[1] "0709 Lamp5 Gaba_1"
[1] 0.75
[1] "0803 Sst Gaba_10"
[1] 0.8
[1] "0740 Pvalb Gaba_3"
[1] 0.45
[1] "0641 Vip Gaba_5"
[1] 0.4
[1] "0645 Vip Gaba_6"
[1] 0.05
[1] "0708 Lamp5 Gaba_1"
[1] 0.15
[1] "0733 Pvalb chandelier Gaba_1"
[1] 0.2
[1] "0624 Vip Gaba_1"
[1] 0.05
[1] "0797 Sst Gaba_8"
[1] 0.15

### Merge all qualified cell types from sections  
**Excitatory clusters**

In [5]:
df_list <- list(df24, df23, df22, df21, df20)      
#merge all data frames together
df<-Reduce(function(x, y) merge(x, y, all=TRUE), df_list)  
df

   cluster                      %24  %23  %22  %21  %20
1  0003 CLA-EPd-CTX Car3 Glut_1   NA   NA   NA 0.68 0.64
2  0004 CLA-EPd-CTX Car3 Glut_1   NA 0.74   NA 0.79   NA
3  0007 IT EP-CLA Glut_1          NA   NA   NA   NA 0.92
4  0026 L5/6 IT TPE-ENT Glut_2    NA 0.55   NA   NA   NA
5  0061 L5 IT CTX Glut_3          NA   NA   NA   NA 0.73
6  0067 L4/5 IT CTX Glut_1        NA 0.47   NA   NA   NA
7  0074 L4/5 IT CTX Glut_1      0.57 0.54 0.55 0.56 0.51
8  0079 L4/5 IT CTX Glut_2      0.51   NA 0.44 0.58 0.62
9  0080 L4/5 IT CTX Glut_2      0.40   NA   NA   NA   NA
10 0086 L4/5 IT CTX Glut_3      0.89 0.92   NA   NA   NA
11 0092 L4/5 IT CTX Glut_4      0.53 0.51   NA   NA   NA
12 0109 L2/3 IT CTX Glut_2      0.80 0.82 0.81 0.86 0.85
13 0114 L2/3 IT CTX Glut_3      0.69   NA   NA   NA   NA
14 0116 L2/3 IT CTX Glut_3      0.72 0.71   NA 0.51   NA
15 0359 L5 ET CTX Glut_2          NA 0.62   NA   NA   NA
16 0375 L5 ET CTX Glut_5          NA 0.69   NA   NA   NA
17 0436 L6 CT CTX Glut_1          NA   NA 0.32 0.33   NA
18 0439 L6 CT CTX Glut_1          NA   NA   NA 0.59 0.50
19 0443 L6 CT CTX Glut_2          NA   NA   NA 0.60   NA
20 0453 L6 CT CTX Glut_5          NA   NA   NA   NA 0.76
21 0455 L6 CT CTX Glut_5          NA   NA   NA 0.66 0.57

In [6]:
write.csv(df, "./temp/filter-exc.csv",row.names = FALSE)

**Inhibitory clusters**

In [7]:
dfi_list <- list(dfi24, dfi23, dfi22, dfi21, dfi20)      
#merge all data frames together
dfi<-Reduce(function(x, y) merge(x, y, all=TRUE), dfi_list)  
dfi

   cluster           %24  %23  %22  %21  %20
1  0624 Vip Gaba_1   0.75   NA   NA   NA   NA
2  0641 Vip Gaba_5     NA   NA 0.71   NA   NA
3  0645 Vip Gaba_6   0.74   NA   NA   NA 0.83
4  0709 Lamp5 Gaba_1   NA   NA 0.73   NA   NA
5  0740 Pvalb Gaba_3 0.59 0.80   NA 0.62 0.69
6  0741 Pvalb Gaba_3 0.71   NA   NA   NA   NA
7  0742 Pvalb Gaba_3 0.73 0.85   NA   NA   NA
8  0743 Pvalb Gaba_4   NA   NA   NA   NA 0.48
9  0747 Pvalb Gaba_4   NA   NA   NA   NA 0.76
10 0754 Pvalb Gaba_8   NA   NA   NA 0.74 0.86
11 0811 Sst Gaba_13    NA   NA   NA 0.65   NA

In [8]:
write.csv(dfi, "./temp/filter-inhib.csv",row.names = FALSE)